
CREATE TABLE parent
(
    id BIGSERIAL PRIMARY KEY,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE category
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    FOREIGN KEY(pareantId) REFERENCES parent(id) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE product
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    image VARCHAR(255) NOT NULL,
    FOREIGN KEY(pareantId) REFERENCES category(id) NOT NULL,
    featured boolean not null default 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE providers
(
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE product_providers
(
    id BIGSERIAL PRIMARY KEY,
    FOREIGN KEY(productId) REFERENCES product(id) NOT NULL,
    FOREIGN KEY(providerId) REFERENCES providers(id) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);